server:
  port: 8080

spring:
  application:
    name: oa-service

  config:
    import: optional:nacos:oa-service.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 'zyx251026'

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        fail-fast: false
        username: nacos
        password: nacos
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        file-extension: yml
        import-check:
          enabled: false
        username: nacos
        password: nacos

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  elasticsearch:
    enabled: true
    rest:
      uris: http://localhost:9200

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: com/southwind/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.southwind: debug